apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cstoredicom-deployment
    namespace: cstoredicom
    labels:
      app: cstoredicom
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: cstoredicom
    template:
      metadata:
        namespace: cstoredicom
        labels:
          app: cstoredicom
      spec:
        containers:
        - name: dicomstorescp
          image:  dicomdemos/dicomstorescp:1.0
          ports:
          - containerPort: 11112
          imagePullPolicy: Never
          resources:
            requests:
              memory: "1G"
              cpu: "0.5"
            limits:
              memory: "2G"
              cpu: "1"

- apiVersion: v1
  kind: Service
  metadata:
    name: cstoredicom-service
    namespace: cstoredicom
  spec:
    selector:
      app: cstoredicom
    ports:
      - name: tcp-port
        port: 11112
        targetPort: 11112
        protocol: TCP

# Run following command to to add to tcp-ingress
# kubectl patch configmap tcp-services -n ingress-nginx --patch '{"data":{"4040":"default/cstoredicom-service:11112"}}'
# Reference https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/
