apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cstoredicom-deployment
    namespace: cstoredicom
    labels:
      app: cstoredicom
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: cstoredicom
    template:
      metadata:
        namespace: cstoredicom
        labels:
          app: cstoredicom
      spec:
        containers:
        - name: dicomstorescp
          image:  dicomdemos/dicomstorescp:1.0
          ports:
          - containerPort: 11112
          imagePullPolicy: Never
          resources:
            requests:
              memory: "1G"
              cpu: "0.5"
            limits:
              memory: "2G"
              cpu: "1"

- apiVersion: v1
  kind: Service
  metadata:
    name: cstoredicom-service
    namespace: cstoredicom
  spec:
    selector:
      app: cstoredicom
    ports:
      - name: tcp-port
        port: 11112
        targetPort: 11112
        protocol: TCP
# - apiVersion: networking.k8s.io/v1 
#   kind: Ingress 
#   metadata:
#     name: cstoredicom-ingress
#     namespace: cstoredicom
#     annotations: 
#       nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#       nginx.ingress.kubernetes.io/ssl-redirect: "true"
#   spec:
#     ingressClassName: nginx
#     ports:
#     - name: proxied-tcp-9000
#       port: 80
#       targetPort: 11112
#       protocol: TCP    
