apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: cstoredicom

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cstoredicom-deployment
    namespace: cstoredicom
    labels:
      app: cstoredicom
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: cstoredicom
    template:
      metadata:
        namespace: cstoredicom
        labels:
          app: cstoredicom
      spec:
        containers:
        - name: dicomstorescp
          image:  dicomdemos/dicomstorescp:1.0
          ports:
          - containerPort: 11112
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512M"
              cpu: "0.5"
            limits:
              memory: "1G"
              cpu: "1"

- apiVersion: v1
  kind: Service
  metadata:
    name: cstoredicom-service
    namespace: cstoredicom
  spec:
    selector:
      app: cstoredicom
    ports:
      - name: tcp-port
        port: 11112
        targetPort: 11112
        protocol: TCP
# Created config map to for routing tcp traffic
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: tcp-services
    namespace: ingress-nginx
  data:
    4040: "cstoredicom/cstoredicom-service:11112"        

# Run following command to to add to tcp-ingress
# Edit ingress-nginx-controller service add below entries 
#  - name: proxied-tcp-4040
#       port: 4040
#       targetPort: 9000
#       protocol: TCP
# 'kubectl edit svc ingress-nginx-controller -n ingress-nginx' 

# Edit ingress-nginx-controller deployment add command line parameter to use 'tcp-services' configmap
#  args:
#     - --tcp-services-configmap=ingress-nginx/tcp-services
# 'kubectl edit deploy ingress-nginx-controller -n ingress-nginx'

# More informaton of adding tcp ingress is @ https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

